### ISSUE TITLE
Migrate posts/pages from the WordPress site

### ISSUE THREAD

**Issue by coyotebush** [CPLUG/cplug.org-old#1]

**Comment by xiongchiamiov** [comment]
Ah, that was what stopped me when I wanted to do this [a while back](https://github.com/xiongchiamiov/cplug.org).  There [do seem to be](https://duckduckgo.com/?q=jekyll+import+wordpress) a number of tools for it now, which is nice.

**Comment by coyotebush** [comment]
Even the Wordpress XML export doesn't look too bad. But thanks for the reminder, we should steal from / build on top of what you've done.

**Comment by coyotebush** [comment]
I tried a few options.
- [exitwp](https://github.com/thomasf/exitwp) works with the exported XML file, but in converting to Markdown it loses some line breaks: 06937625366fb480988d0618feb9a4abee02c340
- [jekyll-import](http://import.jekyllrb.com/docs/wordpress/) works with the database directly (I figured out how to access the old MySQL database and made a copy), and seems to keep the HTML as-is: 0b2f2eb513bfd2dafd668deec42780e97c5c8138
- [wordpress-to-jekyll-exporter](https://github.com/benbalter/wordpress-to-jekyll-exporter) runs inside WordPress and preserves the HTML to the point of retaining Google Analytics code (maybe I could disable that plugin before exporting, though): 22eeb2a0698d70393a326fec0d19401473a1378d

Opinions on the results? Should I look at any other approaches?

**Comment by coyotebush** [comment]
The last option is looking best to me now, since it
- does a reasonable Markdown conversion (and preserves `<br>`s in the result using trailing spaces)
- converts more pages than either of the other options
- makes the permalinks match

Need to preserve images/files (mostly from http://cplug.org/t/uploads/, some old things in http://cplug.org/img/, maybe others scattered around).
