### ISSUE TITLE
Update the alum page.

### ISSUE THREAD

**Issue by brotatos** [CPLUG/cplug.org-old#10]

**Comment by frewsxcv** [comment]
> If you’re an alumni and would like to be included here send your name, current job situation, current distro, and anything else you’d like on here to mgius “at” calpoly “dot” edu

We should probably stop emailing @mgius 's old email

**Comment by xiongchiamiov** [comment]
Could tell them to post an issue here.  Or even better, a pull request. :)

**Comment by icco** [comment]
Fuck, I'll do this.
