### ISSUE TITLE
Make it look nice

### ISSUE THREAD

**Issue by coyotebush** [CPLUG/cplug.org-old#2]
Could steal from https://github.com/xiongchiamiov/cplug.org, or pick something from http://jekyllthemes.org/, or try to match the existing site. Doesn't need to be too fancy, I guess.

@brotatos any motivation to work on this?

**Comment by brotatos** [comment]
Style isn't terribly important so long as we can get word out about CPLUG events.

I think it's in our best interests to just pick out a jekyll theme and move on to content. (We could always come back and style it later.)

**Comment by brotatos** [comment]
Gonna go with [Kasper](https://github.com/rosario/kasper). Will work on integrating it soon.
